CREATE DATABASE COLLEGE_DB;
CREATE TABLE FACULTY(FUCULTY_ID INT, FACULTY_NAME VARCHAR(100), SUBJECT VARCHAR(30), SALARY INT);
INSERT INTO FACULTY VALUES(123, 'Nita', 'Math', 30000);
INSERT INTO FACULTY VALUES(143, 'Vasu', 'Chemistry', 40000);
INSERT INTO FACULTY VALUES(154, 'Arti', 'DS', 80000);
SELECT FACULTY_NAME, SUBJECT FROM FACULTY;





