CREATE DATABASE ECOMMERCE_DB;
CREATE TABLE PRODUCT1(PRODUCT_ID INT, PRODUCT_NAME VARCHAR(100), PRICE INT, IS_AVAILABLE INT);
INSERT INTO PRODUCT1 VALUES(111, 'Oneplus', 5000, 0);
INSERT INTO PRODUCT1 VALUES(111, 'realme', 9000, 1);
INSERT INTO PRODUCT1 VALUES(111, 'oppo', 5000, 1);
SELECT * FROM PRODUCT1 WHERE IS_AVAILABLE =1;

