CREATE DATABASE HR_DB1;
CREATE TABLE EMPLOYEE(EMP_ID INT, EMP_NAME VARCHAR(100), DEPARTMENT VARCHAR(50), SALARY INT);
INSERT INTO EMPLOYEE VALUES(122, 'Sarkha', 'Computer', 4000);
INSERT INTO EMPLOYEE VALUES(132, 'Harsha', 'Editor', 5000);
INSERT INTO EMPLOYEE VALUES(122, 'Shweta', 'Computer', 4000);
SELECT * FROM EMPLOYEE;

