CREATE DATABASE PROJECT_DB;
CREATE TABLE EMPLOYEE (EMP_ID INT, EMP_NAME VARCHAR(100));
INSERT INTO EMPLOYEE VALUES(123, 'Sarikha');
INSERT INTO EMPLOYEE VALUES(125, 'Shweta');
INSERT INTO EMPLOYEE VALUES(126, 'Harsha');

CREATE TABLE PROJECT1(PROJECT_ID INT, PROJECT_NAME VARCHAR(100), EMP_ID INT);
INSERT INTO PROJECT1 VALUES(143, 'CrowdFunding', 188);
INSERT INTO PROJECT1 VALUES(333, 'StudentAttendance', 15);
INSERT INTO PROJECT1 VALUES(123, 'CafeManagmentSystem', 123);
SELECT * FROM PROJECT1;



