CREATE DATABASE STARTUP_DB;
CREATE TABLE EMPLOYEE(EMP_ID INT, EMP_NAME VARCHAR(100), JOINING DATE);
INSERT INTO EMPLOYEE VALUES(123, 'Sarikha', '2023-04-20');
INSERT INTO EMPLOYEE VALUES(123, 'Komal', '2022-05-10');
SELECT EMP_NAME, JOINING FROM EMPLOYEE;

