CREATE DATABASE TRAINING_COMPANY;
CREATE TABLE STUDENTS(STUDENT_ID INT, NAME VARCHAR(100), EMALIL VARCHAR(100));
INSERT INTO STUDENTS VALUES(12, 'Sarikha', 'psarika@gmail.com');
INSERT INTO STUDENTS VALUES(123, 'Shravani', 'shravani@gmailcom');
SELECT * FROM STUDENTS;

CREATE TABLE COURSE(COURSE_ID INT, COURSE_NAME VARCHAR(100), COURCE_DURATION VARCHAR(100));
INSERT INTO COURSE VALUES(4732, 'Java', '1-month');
INSERT INTO COURSE VALUES(4321, 'HTML', '1.5-month');
SELECT * FROM COURSE;
 


